[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "analytics/script.js"
  to     = "https://cloud.umami.is/script.js"
  status = 200
  force  = true

[[redirects]]
  from   = "analytics/api/*"
  to     = "https://cloud.umami.is/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200